### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by palnabarun** [UdacityMobileWebScholarship/showcase-app#1]
Currently, the Readme contains the boilerplate contents of CRA. That needs to be replaced with appropriate content for the project.

**Comment by highskillzz** [comment]
I will take this up but to what should I convert this to?

Like should I change the readme to the description and a few commands on how to run it will be good enough?

**Comment by ritikrishu** [comment]
Hi @highskillzz !
Glad you volunteered, actually this is an initial setup so I've assigned this to myself. Once it gets a skeleton and basic structure. From there you can suggest/edit improvements. I'll make sure to tag you in the PR.

**Comment by ritikrishu** [comment]
Pull Request is up for review #8
