### ISSUE TITLE
Server Side Setup

### ISSUE THREAD

**Issue by divyamrastogi** [UdacityMobileWebScholarship/showcase-app#17]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

There's no server as of now.

**Expected behavior:**

We would like an Express server that would handle some of the API calls.
This should include an integration with **MongoDB** as well.

**Comment by raveesh-me** [comment]
Should we not have an offline setup guide instead?
Let's collaborate on a wiki guide for installing the project environment on localhost like in the course and worry about server stuff "after" we have built the application

**Comment by divyamrastogi** [comment]
Closing this because we're going with Firebase.
