### ISSUE TITLE
API Creation

### ISSUE THREAD

**Issue by divyamrastogi** [UdacityMobileWebScholarship/showcase-app#18]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**

We'll keep adding features/API requests
**Expected behavior:**

Currently, I can think of the following APIs:

1. User Registration/Login (POST)
2. Admin Registration/Login (POST)
3. Project Registration (POST)
4. Project Approval (PUT)
5. Project Info (GET)

Let's keep updating this before picking it up.

Pre-requisite:
https://github.com/UdacityMobileWebScholarship/showcase-app/issues/17

**Comment by sb7896** [comment]
I would like to work on API creation part

**Comment by ritikrishu** [comment]
where do you think we should deploy our server to and what services should we use for different stuff.
basically, I want to know if we'll be using firebase for our 360 requirements such as functions, authentication. As it quite easy to setup authentication with fb, github, google and few other integrations using firebase.

**Comment by palnabarun** [comment]
@ritikrishu I think Firebase can be used for Auth and DB. For deployment, we can use now.sh or heroku. I prefer now.sh. We can go with the OSS Plan. More info [here](https://zeit.co/pricing)

**Comment by divyamrastogi** [comment]
@ritikrishu @palnabarun : Honestly, I've never used Firebase, so I might not know it's true capabilities. But from what I've read it can give us a scalable database and features like authentication. I think our use case should suffice the use of Firebase.

^ now.sh looks good for the Frontend. Let me just close the issue about creating a NodeJs server.

**Comment by highskillzz** [comment]
I have a question why are we using firebase for users when we can do everything at a single place? Just curious

**Comment by divyamrastogi** [comment]
@ritikrishu @blenderskool : I'm actually sold on Firebase. It solves a lot of problems for us, we don't have to worry about deployments.
Most people will be new to Firebase, I know that. But I think it's a good opportunity to learn a new technology.

**Comment by blenderskool** [comment]
@anurag-majumdar Yes we should use Firestore, as it allows us to perform basic queries. Firestore web also supports offline data storage using IndexedDB, which can be used or we can do that ourselves based on what we have learnt in the course.

**Comment by anurag-majumdar** [comment]
@blenderskool Exactly! This will be a nice thing to explore. So its going to be the latest version of Firebase then.

**Comment by ritikrishu** [comment]
Yay!🎉🎉
I was really hoping that we go with firebase because I am very much impressed by it's services so far and really want to learn more about it!

**Comment by raveesh-me** [comment]
Firebase requires writing access rules within the console. Make that available in a separate project folder as well so that we could get a better experience

**Comment by ritikrishu** [comment]
It also takes `database.rules.json` file to define access rules. We'll use that.

**Comment by ritikrishu** [comment]
The list of components from firebase will be growing slowly.
- to run client only, no firebase specific thing required...as you can directly develop using staging env on server.
- to run server locally, firebase CLI.
- to run whole project locally(both client and server) firebase CLI

Exact components that I think will eventually be there in our project will be _functions_, _hosting_, _push messaging_, _craslytics_, _realtime db_.
Note: although we are using realtime db, we won't be making direct connections from the client itself, instead proxy it through our server API handlers to give it a REST like architecture.

**Comment by ritikrishu** [comment]
Yeah and firestore for keep the file uploads in future.
IMO, we should start building the basic app first (i.e. no PWA, no advance features such as in app rendering and all). From there, we can divide work and some of us will be making it a PWA while others can help with the _"advance in app features"_.
Also, you don't need to learn all the things this project will be using, so take it easy...start with the part that attracts you more! You can always move up into other parts.

**Comment by realslimshanky** [comment]
Closing this issue since we have decided to user Firebase now.
Similar discussion: https://github.com/UdacityMobileWebScholarship/showcase-app/issues/17#issuecomment-383792377
