### ISSUE TITLE
Lack of contribution guidelines

### ISSUE THREAD

**Issue by palnabarun** [UdacityMobileWebScholarship/showcase-app#2]
The project does not have any guidelines specifying how to start contributing to the project.

**Comment by sounak07** [comment]
I guess the moderators are going to update that soon.

**Comment by palnabarun** [comment]
@sounak07  Yes, we will shortly. :)

**Comment by ritikrishu** [comment]
Pull Request is up for review #8

**Comment by palnabarun** [comment]
Fixed with #8
