### ISSUE TITLE
What will be the structure of the Client code components and where will be the unit test files placed

### ISSUE THREAD

**Issue by nikitasharma2692** [UdacityMobileWebScholarship/showcase-app#24]
Hello everyone,

As we are ready with the mockups,  we need to  have guidelines on how the structure of the client code will look, and where test files will be placed.

For example 

1. Structure type 1

MyProject 
->Components
--> App
 ---> App.jsx
---> App.scss
--->App.spec.js
--->App.snapshot.js
-->Dashboard
 ---> Dashboard.jsx
---> Dashboard.scss
--->Dashboard.spec.js
--->Dashboard.snapshot.js
->Constants
->Actions
->Reducers
.....

2. Structure Type 2
->test
-->Components
--->App
---->App.spec.js
---->App.snapshot.js
--->Dashboard
---->Dashboard.spec.js
---->Dashboard.snapshot.js
->Components
--> App
 ---> App.jsx
---> App.scss

-->Dashboard
 ---> Dashboard.jsx
---> Dashboard.scss

->Constants
->Actions
->Reducers
.....

Kindly share your thoughts

**Comment by ritikrishu** [comment]
client
   --assets
   --sdk
      -- api-services
      -- ui-kit
      -- util services
      -- redux?
    --projects
        --project-list
           --components
           ProjectList.js
        --add-project
           --components
           AddProject.js
         index.js
     --some other module
        --feature set 1
            --its components
            FeatureSet1Component.js
        --feature set 2
            --its components
            FeatureSet2Component.js
        index-exporting-required-classes-and-variables-from-this-module.js
   --App.js
   --App.css
   --index.js
   --index.css
  ...


cc: @divyamrastogi @PrabhanshuAttri @realslimshanky @palnabarun @ParthS007 @shubhshrma

**Comment by divyamrastogi** [comment]
I was wondering if we really need the client folder anymore since we're not using a conventional server.

**Comment by ritikrishu** [comment]
Oh yes! totally missed it 😃

**Comment by nikitasharma2692** [comment]
@ritikrishu What about the test case files ? where will they belong ? that is not mentioned in your structure ?

**Comment by ritikrishu** [comment]
test files reside alongside their respective implementation files!

**Comment by realslimshanky** [comment]
I guess we need to revert back the original project structure now since we are using firebase.
