### ISSUE TITLE
setup node-express app and static hosting for server and client on firebase

### ISSUE THREAD

**Issue by ritikrishu** [UdacityMobileWebScholarship/showcase-app#26]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

Follow up from #7 #17
After discussion, we decided to go with firebase for different app services. For now, Client and Server setup is required.

**Comment by ritikrishu** [comment]
I am gonna take this up myself! Should give a PR today when I get some time.

**Comment by ritikrishu** [comment]
Oh, this was quite easy, took literally minutes!
Now I do strongly believe that we choose that right thing.
client will be served - https://showcase-app-6aace.firebaseapp.com/
test server handlers - 
without cdn -> https://showcase-app-6aace.firebaseapp.com/api/non-cached-timestamp
with cdn -> https://showcase-app-6aace.firebaseapp.com/api/cached-timestamp

will put the PR up shortly!

**Comment by realslimshanky** [comment]
Closing this issue since we have decided to user Firebase now.
Similar discussion: https://github.com/UdacityMobileWebScholarship/showcase-app/issues/17#issuecomment-383792377
