### ISSUE TITLE
Add link to install yarn package manager

### ISSUE THREAD

**Issue by sb7896** [UdacityMobileWebScholarship/showcase-app#27]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There is no Note to install **Yarn** package manager

**Expected behavior:**
Add Note to install **Yarn** package manager, as our application uses it.

**Comment by ritikrishu** [comment]
This is not expected as of now. Please see https://github.com/UdacityMobileWebScholarship/showcase-app/pull/28#issuecomment-384451711
