### ISSUE TITLE
Design guidelines readme file

### ISSUE THREAD

**Issue by anurag-majumdar** [UdacityMobileWebScholarship/showcase-app#31]
@realslimshanky @divyamrastogi @palnabarun @nikitasharma2692 @PrabhanshuAttri 
Hi everyone, @blenderskool and I are currently working on a design guideline file in markdown. In that file we are going to provide a link to all the images stored in the google photos cloud.

This way we can avoid storage of multiple images on the project repository but yet provide a link to each of the screens in the file.

Also, the file will contains some important points regarding the design to be followed throughout the project. We are making the changes and uploading it as a file to the repo directly.

Let us know your thoughts on this?

**Comment by ritikrishu** [comment]
Fixed via #32
