### ISSUE TITLE
Restoring project structure

### ISSUE THREAD

**Issue by realslimshanky** [UdacityMobileWebScholarship/showcase-app#36]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
The project repository was separated to a client-server model and hence a lot of code was shifted to `/client` folder.

**Expected behavior:**
Since we have decided to use Firebase for backend the restructure can be reversed to the original state.

**Steps to reproduce:**
None

**Comment by anurag-majumdar** [comment]
I can help contribute on this part. I guess we need to bring out the contents of the client folder and set it in the repo's main directory itself?

**Comment by divyamrastogi** [comment]
@anurag-majumdar : I was working on another issue here and had already moved back to the old structure.

**Comment by divyamrastogi** [comment]
@realslimshanky, @palnabarun : Can you guys review once?
