### ISSUE TITLE
[Frontend] Create a Tile Component

### ISSUE THREAD

**Issue by divyamrastogi** [UdacityMobileWebScholarship/showcase-app#50]
**I'm submitting a ...**
- [x] feature request

**Current behavior:**
We need a Tile component so as to reuse on the home page based on the [use case](https://photos.app.goo.gl/fwjGFaiPL3HqnAuu6)
![image](https://user-images.githubusercontent.com/1598017/39795980-8712b228-5371-11e8-9213-8c1c52b83995.png)

**Expected behavior:**
Anyone should be able to use the Tile component in this way:
```
<Tile color="#fa8243">All</Tile>
```

**Comment by realslimshanky** [comment]
@saini-himanshu nice. I'm assigning this to you. Please raise a PR soon.
