### ISSUE TITLE
Create an Avatar component

### ISSUE THREAD

**Issue by divyamrastogi** [UdacityMobileWebScholarship/showcase-app#53]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request

**Current behavior:**
There's no `Avatar` component. Each user will have an Avatar which can then be used to show Collaborators, Project Owners and Admins.

**Expected behavior:**
We need an `Avatar`component that could be used this way and looks like: 
**Variation 1:**
![image](https://user-images.githubusercontent.com/1598017/39801941-6940206e-538a-11e8-810f-0c0e34ad857b.png)

**Variation 2:**
![image](https://user-images.githubusercontent.com/1598017/39802151-ec5493d6-538a-11e8-94a3-947a9f94606d.png)

**Variation 3:**
![image](https://user-images.githubusercontent.com/1598017/39802178-02f31c20-538b-11e8-9a9c-c5d042fe090f.png)

```
<Avatar name={name} image={image} align={align} />
```

Options:
`name`: An optional field, when not provided, it won't display the Avatar's text below the image.
`image`: The image to display in the `Avatar`.
`align`: Text alignment can be `bottom|right`
`onClick`: In case there is something that needs to be done.

**Comment by blenderskool** [comment]
Additionally clicking on Variation 1 or 3 should open their profile if possible.

**Comment by divyamrastogi** [comment]
That should be simple enough to do. We'll add an `onClick` handler.

**Comment by Rohanhacker** [comment]
material ui already have an avatar component 'material-ui/Avatar'

**Comment by divyamrastogi** [comment]
@Rohanhacker : Thanks for pointing that out! I wasn't really familiar that it was already there. Closing this. 
@saini-himanshu : Perhaps you could help us out with another issue?
